name: space_metro
description: Learn how to fail fast from this simple flutter game

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/

  fonts:
    - family: AlmendraSC
      fonts:
        - asset: assets/fonts/AlmendraSC-Regular.ttf
          weight: 500
